### ISSUE TITLE
Extract landmarks on videos outside the LRW dataset

### ISSUE THREAD

**Issue by Di1emma** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#1]
Hi,

Thanks for providing the code and pre-trained models. Currently, I would like to evaluate the model using some wild videoes, instead of the testing set provided by the LRW dataset. Would you please tell me how to extract landmarks from my own videoes? Thanks.

**Comment by mpc001** [comment]
Hi, you could use dlib library. Our dlib version is 19.17.0

**Comment by Di1emma** [comment]
Thanks for the reply. Did you use shape_predictor_68_face_landmarks.dat to extract the landmarks? After extract the landmark did you process it further (i.e., normalize, rotate from side to front)? Thanks.

**Comment by mpc001** [comment]
Hi, we used a model trained on 300W/VW and Helen. The raw faces and landmarks are projected to mean face via affine transformation.

**Comment by Flash-321** [comment]
Hi, how should I deal with the situation that dlib do not recognize any face in one frame?
