### ISSUE TITLE
这个是输入几张图片给模型？

### ISSUE THREAD

**Issue by Bruno-bai** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#11]
是固定输入10张照片给模型吗？还是说嘴唇的照片数量不固定？不固定的这种输入是怎么实现的？

**Comment by mpc001** [comment]
Hi,

The question is asking how to load variable length of inputs. What we did is to custom collate function in the class of DataLoader. Please check it for details:
https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/lipreading/dataset.py#L118-L133
