### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by Fdeshnawy** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#12]
I am working on a small project and the training code will be helpful
please post it if available if not give me a hint please for the loop to be done

**Comment by ShashiAdhikari** [comment]
@

> I am working on a small project and the training code will be helpful
> please post it if available if not give me a hint please for the loop to be done
https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/issues/6

Issue 6 explains that this is for testing code and there is no training code. I am also trying to figure out about the training code

**Comment by mpc001** [comment]
Hi,

the training code has been released.

Please check it.
