### ISSUE TITLE
How to load audio data?

### ISSUE THREAD

**Issue by ZhangYikaii** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#13]
Thank you for sharing such nice code.

My question is: how to extract audio data **from an MP4 file** in the preprocessing stage? In [this](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/tree/master/preprocessing) folder, I just found the ones related to the images.

Thanks again. Looking forward to your early reply.

**Comment by mpc001** [comment]
Hi, the mp4 audio data is extracted in line https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/lipreading/dataset.py#L84

**Comment by ZhangYikaii** [comment]
Thank you very much!
