### ISSUE TITLE
Can replace gru with transformer?

### ISSUE THREAD

**Issue by hegc** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#15]

**Comment by mpc001** [comment]
Hi, yes, both are suitable for sequence modelling.

**Comment by hegc** [comment]
I replaced gru with transformer, but the model did not converge...If you have time to try, please share it, thank you.

**Comment by mpc001** [comment]
Hi, when using transformer, I suggest that you could carefully tune the warm-up stage such as peak learning rate and number of steps.
