### ISSUE TITLE
I don't have a json model

### ISSUE THREAD

**Issue by kategia** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#17]
Hello,
probably a stupid question but in the main function I want to use the pretrained model (.pth.tar) format since I dont have a model in json . Do I necessarely have to use a json model in order to start the training? If not do you know any way to fix it?
Thank you

line 169, in get_model_from_json
    assert args.config_path.endswith('.json') and os.path.isfile(args.config_path), \
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by mpc001** [comment]
Hi, kategia,

We save the configuration in a format of json. You could acess the configuration (.json) at the folder of [configs](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/tree/master/configs).

If you would like to evaluate the model, you could specify the  pretrained mode (.pth.tar) to *`--model-path`*.

**Comment by kategia** [comment]
Thank you for your response! I now get     raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by mpc001** [comment]
Hi, there

This thread [(30664)](https://github.com/pytorch/pytorch/issues/30664) may help

**Comment by kategia** [comment]
Hello again,
I just removed the .cuda() part from extract_feats=args.extract_feats).cuda() since for now I run it locally thank you for the thread though. I get this error     
line 215, in main 
model, optimizer, epoch_idx, ckpt_dict = load_model(args.model_path, model, optimizer)
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
KeyError: 'optimizer_state_dict'

I haven't modyfied the optimizer parameters here they are
parser.add_argument('--optimizer',type=str, default='adamw', choices = ['adam','sgd','adamw'])
Any idea what could fix this? Thank you

**Comment by mpc001** [comment]
Hi, kategia,

Could you tell me which checkpoint file did you use?

**Comment by kategia** [comment]
Hello,
sure its the resnet18_mstcn(adamw_s3) model -->lrw_resnet18_mstcn_adamw_s3.pth.tar

**Comment by mpc001** [comment]
Hi,

The checkpoint only includes the weight of model. That's why no keys in optimiser.

If you are testing the model or initialise from our model, please leave *'--init-epoch'* to 0.
 
https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/main.py#L215-L219 is for loading model to resume training. The previous checkpoints, which includes the keys in optimiser, could be accessed in the folder of [train_logs](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/tree/master/train_logs)

**Comment by kategia** [comment]
Yep my bad you are totally right.
One last thing,
when I try to train the model I get the following error
  File "C:/lipreading/Lipreading_using_Temporal_Convolutional_Networks/main.py", line 240, in main
    model = train(model, dset_loaders['train'], criterion, epoch, optimizer, logger)
  File "C:/Lipreading_using_Temporal_Convolutional_Networks/main.py", line 135, in train
    for batch_idx, (input, lengths, labels) in enumerate(dset_loader):
    ...............
        assert os.path.isfile( filepath ), "Error when trying to read txt file, path does not exist: {}".format(filepath)
AssertionError: Error when trying to read txt file, path does not exist: C:\Lipreading_using_Temporal_Convolutional_Networks\datasets\visual_data\ABOUT\train\ABOUT_00849.txt

In this folder I have the ABOUT folder with the processed images(npz) format and no txt file. Where does the error come from?Thank youuu

**Comment by mpc001** [comment]
Hi,

The annonation file (.txt) is in the original LRW-BBC dataset. Also, please note that the splitting symbol for file path is different between windows and unix.

**Comment by evialv** [comment]
great thanks
