### ISSUE TITLE
Extract mean face on my own dataset

### ISSUE THREAD

**Issue by zzgg1** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#2]
Hi, Thanks for you code! After reading the paper, I am not quite sure the meaning of mean face parameter, and if I hope to use with my own data, how to extract the mean face parameter before training?

**Comment by mpc001** [comment]
Hi,

Mean face refers the mean landmarks for the training set.

If you want to train from scratch, you could recalcuate the mean landmarks of your own dataset. If your model is initialised from our pre-trained model, you could use the same mean face as ours. Please check this:
https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/preprocessing/20words_mean_face.npy
