### ISSUE TITLE
The code for the Knowledge Distillation loss

### ISSUE THREAD

**Issue by YairDeitcher** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#24]
Hi.

Did you publish the code for the Knowledge Distillation loss? I couldn't find it in the code. 
If it is not there, could you please publish the code?

Thanks

**Comment by PussyCat0700** [comment]
Are you looking for the code for the paper "TOWARDS PRACTICAL LIPREADING WITH DISTILLED AND EFFICIENT MODELS" too? I haven't found the code either, but by any chances did you finally it is released? Thank you!

**Comment by BaochaoZhu** [comment]
Are you looking for the code for the paper "TOWARDS PRACTICAL LIPREADING WITH DISTILLED AND EFFICIENT MODELS" too? I haven't found the code either, but by any chances did you finally find where it is released? Thank you!
