### ISSUE TITLE
Why does training data need babble noise?

### ISSUE THREAD

**Issue by ZhangYikaii** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#27]
Hi,

I'm a beginner in this field. Why do you need babble noise during training? That's what's happening [here](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/47872c9a7a357b70a4adc97e51658c1e43fde8d9/lipreading/dataloaders.py#L29).

Thank you very much.

**Comment by mpc001** [comment]
Hello, noise injection is a data augmentation for audio-only and audio-visual models, which helps stabilise the model in a noisy environment.
