### ISSUE TITLE
UnboundLocalError: local variable 'tcn_options' referenced before assignment

### ISSUE THREAD

**Issue by AhmedWael74** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#3]
While evaluating the module the code always crashes due to this error,
UnboundLocalError: local variable 'tcn_options' referenced before assignment
as it requires the tcn_options variable to be global.
How can i fix this please ?
 `def get_model():
    if os.path.exists(args.config_path):
        args_loaded = load_json( args.config_path)
        args.backbone_type = args_loaded['backbone_type']
        args.width_mult = args_loaded['width_mult']
        args.relu_type = args_loaded['relu_type']
        tcn_options = { 'num_layers': args_loaded['tcn_num_layers'],
                        'kernel_size': args_loaded['tcn_kernel_size'],
                        'dropout': args_loaded['tcn_dropout'],
                        'dwpw': args_loaded['tcn_dwpw'],
                        'width_mult': args_loaded['tcn_width_mult'],
                      }
    return Lipreading( num_classes=args.num_classes,
                       tcn_options=tcn_options,
                       backbone_type=args.backbone_type,
                       relu_type=args.relu_type,
                       width_mult=args.width_mult,
                       extract_feats=args.extract_feats).cuda()
`

**Comment by mpc001** [comment]
Could you share the information more? (conda or system python, python version, cuda version, Linux version, and distributions)

**Comment by AhmedWael74** [comment]
system python, Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by mpc001** [comment]
Hi, I don't have a pc with win32 environment now. I tested with python3.7.2, python 3.6.9 and python 3.5.2 on Ubuntu 16.04 and they are fine. Is it possible for you to change an operating system? and can you check if you followed the instruction as described:
https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks#how-to-test

**Comment by AhmedWael74** [comment]
I don't think the environment is the issue though but I will try to change the OS. However can you elaborate more on the instructions as I may be misunderstanding the steps or so

**Comment by mpc001** [comment]
Sure.

- The first step is to download the tracked points - since you're using your own data you have to track them as mentioned above. 

- Second step is the preprocessing, which points to this script: https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/tree/master/preprocessing. `<DATA-DIRECTORY>` points to the directory of your preprocessed data.

- Third step is the model downloading. Pre-trained models are listed in https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks#model-zoo. `<MODEL-PATH>` is the file path of your downloaded model. You could find corresponding configuration files `<MODEL-JSON-PATH>` in https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/tree/master/configs

- The last step is to test the model
```Shell
CUDA_VISIBLE_DEVICES=0 python main.py --config <MODEL-JSON-PATH> \
                                      --model-path <MODEL-PATH> \
                                      --data-dir <DATA-DIRECTORY>
```

**Comment by AhmedWael74** [comment]
Well I am testing on the LRW Data set so I used your landmarks and the preprocessing so I will retry  the whole process, Do I need to extract the pretrained module after installing them and if so what command do I need ?

**Comment by brais-martinez** [comment]
Hi @AhmedWael74 from what I see on your first post, the error happens on the "get_model" function. It seems like this if is False:

https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/main.py#L84

Thus, the issue is args.config_path, which corresponds to this argument:

https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/main.py#L50

if you see the error is elsewhere, please add the error stack

@mpc001 can we add an exception here that helps exit gracefully if the config file is not found/is not json? (also there is a silly typo in l50)

**Comment by mpc001** [comment]
Hi,

@brais-martinez , I've updated a feature which include assertion statements to check if both configuration and model paths exist.

@AhmedWael74, since the issue occurred in `get_model()`, can you check if `--config-path` is pointed correctly?

**Comment by AhmedWael74** [comment]
@mpc001 
@brais-martinez 
Thank you both for your concern and kindness now the error is solved when the --config-path is pointed correctly. 
However the config file for the "resnet18_mstcn_adamw_s3" is still missing.

**Comment by mpc001** [comment]
Hi, @AhmedWael74 

`resnet18_mstcn_adamw_s3` and `resnet18_mstcn` both use the configuration `lrw_resnet18_mstcn.json`

**Comment by AhmedWael74** [comment]
okaay ,thank you very much

**Comment by AhmedWael74** [comment]
Traceback (most recent call last):
  File "F:/BUE/Graduation Project/GitHubCodes/Lipreading_using_Temporal_Convolutional_Networks/main.py", line 119, in <module>
    main()
  File "F:/BUE/Graduation Project/GitHubCodes/Lipreading_using_Temporal_Convolutional_Networks/main.py", line 115, in main
    dset_loaders = get_data_loaders(args)
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataloaders.py", line 40, in get_data_loaders
    ) for partition in ['test']}
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataloaders.py", line 40, in <dictcomp>
    ) for partition in ['test']}
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataset.py", line 29, in __init__
    self.load_dataset()
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataset.py", line 38, in load_dataset
    self._get_files_for_partition()
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataset.py", line 73, in _get_files_for_partition
    self._data_files = [ f for f in self._data_files if f.split('/')[self.label_idx] in self._labels ]
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataset.py", line 73, in <listcomp>
    self._data_files = [ f for f in self._data_files if f.split('/')[self.label_idx] in self._labels ]
IndexError: list index out of range

@mpc001 Can you help me with this error?

**Comment by mpc001** [comment]
Hi, @AhmedWael74 
I think it may because windows uses backslash `\` for the file system delimiter. If this is the cause, can you please replace `.split('/')` with `.split('\\')` in `dataset.py`

**Comment by AhmedWael74** [comment]
I am really sorry for bothering you that much but the errors are overwhelming.
Traceback (most recent call last):
  File "F:/BUE/Graduation Project/GitHubCodes/Lipreading_using_Temporal_Convolutional_Networks/main.py", line 121, in <module>
    main()
  File "F:/BUE/Graduation Project/GitHubCodes/Lipreading_using_Temporal_Convolutional_Networks/main.py", line 117, in main
    dset_loaders = get_data_loaders(args)
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataloaders.py", line 48, in get_data_loaders
    worker_init_fn=np.random.seed(1))for x in ['test']}
  File "F:\BUE\Graduation Project\GitHubCodes\Lipreading_using_Temporal_Convolutional_Networks\lipreading\dataloaders.py", line 48, in <dictcomp>
    worker_init_fn=np.random.seed(1))for x in ['test']}
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\sampler.py", line 96, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by mpc001** [comment]
Hi, @AhmedWael74 
It seems the `.npz` pathnames are not found. Can you please check if you point `<DATA-DIRECTORY>` correctly. The `<DATA-DIRECTORY>` has the following directory structure.
```
<DATA-DIRECTORY>
│
└───ABOUT
│   │   train
│   │   val
│   │
│   └───test
│       │   ABOUT_00001.npz
│       │   ABOUT_00002.npz
│       │   ...
│   
└───ABSOLUTELY
    │   train
    │   ...
```
