### ISSUE TITLE
Question regarding annonation directory

### ISSUE THREAD

**Issue by seunghyeon528** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#30]
Hi, thanks for the code! 

I'm wondering where can I get the txt file which should be included in annonation-direc

thx!

**Comment by mpc001** [comment]
Hi, I think that the original LRW dataset from the LRW website should have timestamps (.txt).

**Comment by ShreyaMaheshwari** [comment]
It doesn't have it. Is there a way to test the model without it?
