### ISSUE TITLE
Extract Embedding

### ISSUE THREAD

**Issue by SahibzadaAdil** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#31]
CUDA_VISIBLE_DEVICES=0 python main.py --extract-feats \
                                      --config-path <MODEL-JSON-PATH> \
                                      --model-path <MODEL-PATH> \
                                      --mouth-patch-path <MOUTH-PATCH-PATH> \
                                      --mouth-embedding-out-path <OUTPUT-PATH>
I tried jpg, npy, npz for image but failed to extract embeddings of mouth patches, May I know what type of file it expects to extract 512-D embedding?

**Comment by mpc001** [comment]
Hi!

We assume mouth patches are saved in a format of npz with a key of "data".

I attach [link](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/lipreading/utils.py#L63-L67) about the function of saving mouth patches. The way of loading data is at [here](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/main.py#L95). Hope it helps!
