### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by IQ17** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#33]
Hi, thanks for the code!

I want to do a test with your pretrained model on the LRW dataset.

Firstly, I run the crop_mouth_from_video.py and got many npz under “$TCN_LIPREADING_ROOT/datasets/visual_data/”
Secondly, I run

"""
CUDA_VISIBLE_DEVICES=0 python main.py \
                                      --config-path “$TCN_LIPREADING_ROOT/configs/lrw_resnet18_mstcn.json” \
                                      --model-path “$TCN_LIPREADING_ROOT/models/lrw_resnet18_mstcn_adamw_s3.pth.tar” \
                                      --data-dir “$TCN_LIPREADING_ROOT/datasets/visual_data/” \
                                      --test 
"""

But I got an error that in

“$TCN_LIPREADING_ROOT/lipreading/preprocess.py [L87](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/47872c9a7a357b70a4adc97e51658c1e43fde8d9/lipreading/preprocess.py#L87) ,  frames actually is of shape (29, 96, 96, 3)

What is wrong in my procedure?

**Comment by ShreyaMaheshwari** [comment]
How did you resolve this?
