### ISSUE TITLE
Ask a question about non-casual tcn

### ISSUE THREAD

**Issue by Leebh-kor** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#37]
Thank you for providing your lip reading research and code. 
I got a question after reading the code and paper you provided. According to the paper, tcn is designed as non-causal, but the code is designed as causal tcn. Non-causal can be designed through some modifications, so there is no problem.
Is the performance presented in the paper casual or non-casual tcn?
Thank you!

**Comment by Leebh-kor** [comment]
Is chomp simply used to match the sequence length of tcn input and output?

**Comment by mpc001** [comment]
Hi @Leebh-kor,

we introduce the `Chomp1d()` class, which allows switching between causal and non-causal designs, and we set `symm_chomp` to true for non-causal design.
