### ISSUE TITLE
Can we do Sentence Prediction for the model?

### ISSUE THREAD

**Issue by hasanm29** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#44]
Hello @mpc001 , thank you for your wonderful code with step by step guide to train and test the model.
I have tried the prediction code provided in issue #10. It provides only one word and the prediction is not correctly given with really low confidence.

Can we predict a sentence {the LRW dataset has multiple words in the video) not just a single word from the trained model?
Kindly share your valuable ideas. Thanks

I said about, it's saying needs :(
![Screenshot 2022-04-25 151148](https://user-images.githubusercontent.com/47795640/165106746-b2b89caa-27df-487d-857a-2cb20d7927bd.png)

**Comment by mpc001** [comment]
Hi @hasanm29 The model can only predict isolated words given a visual speech clip (I explain the reason at #4). You could evaluate your recorded video using our released pre-trained model (https://github.com/mpc001/Visual_Speech_Recognition_for_Multiple_Languages#how-to-test)

For sentence-level lipreading, there're two large-scale audio-visual datasets LRS2 and LRS3. You could check following recent works based on that for a better understanding how to do that. For example:
https://arxiv.org/abs/2201.02184
https://arxiv.org/abs/2109.09536
https://arxiv.org/abs/2110.07603
https://arxiv.org/abs/2202.13084
