### ISSUE TITLE
How to use pretrain model after download from Google drive

### ISSUE THREAD

**Issue by duytran1332002** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#55]
I have downloaded the pretrain model from google and I see the "archive" folder has a lot of files, but I do not see the ".pth" file to use for pretrain.

**Comment by ShreyaMaheshwari** [comment]
Hi! Were you able to figure out how to use the pre-trained model?

**Comment by mpc001** [comment]
Hello, there was an issue when loading checkpoint with `.pth.tar` format. It should be fixed now. Please let me know if any issues.
