### ISSUE TITLE
Not able to evaluate visual-only performance using the pre-processed npz files

### ISSUE THREAD

**Issue by Rathi4research** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#60]
Hi, I did the following steps but got the below error. 
step-1: I executed the crop_mouth_from_video.py from the preprocess directory and got the .npz files.
step-2: Executed the script related to visual-only performance as shown in screen shot 1 and got the error as shown in screen shot 2

**screenshot-1**
![image](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/assets/124800607/13183dd2-d097-4c90-a6ad-3979be06b3a8)

**screenshot-2**
![image](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/assets/124800607/559d29c2-f961-472d-9073-579396db8804)

Also attaching the full log trace as a text file.
[Lipreading_Error.txt](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/files/12640889/Lipreading_Error.txt)

**Comment by mpc001** [comment]
Hi @Rathi4research, thank you for providing the detailed log. Can you please check if any `.npz` files have a shape of (29, 96, 96)? You can load by `np.load(filename)["data"].shape`, where `filename` is a `.npz` file. Also, can you please print the shape of frames at [this link](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/lipreading/preprocess.py#L87)? The frames should have a shape of video length x height x width

**Comment by Rathi4research** [comment]
Thank u so much for your reply. I was able to fix this by changing the input argument from "parser.add_argument('--convert-gray', **default=False**, action='store_true', help='convert2grayscale')" 
to "parser.add_argument('--convert-gray', **default=True**, action='store_true', help='convert2grayscale')"
