### ISSUE TITLE
Regarding "3 weeks to 1 week GPU-time", specify hardware

### ISSUE THREAD

**Issue by njan-creative** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#7]
Can you also give some details of the training hardware required for training the model.

Can you give some details about the measure "1 week GPU time"

**Comment by brais-martinez** [comment]
Yes, it is a single RTX2080. CPU requirements are not high, I believe 2 threads should do, but this also depends on how you store the data.

**Comment by njan-creative** [comment]
Thank you for the details.
