### ISSUE TITLE
Error in pre-processing - help 

### ISSUE THREAD

**Issue by arindam999** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#8]
!python crop_mouth_from_video.py --video-direc "../data/news.mp4" \
                                --landmark-direc "../landmarks/LRW_landmarks" \
                                --save-direc "../datasets" \
                                --convert-gray \
                                --testset-only

idx: 0 	Processing.	ABOUT/test/ABOUT_00001
Traceback (most recent call last):
  File "crop_mouth_from_video.py", line 157, in <module>
    assert sequence is not None, "cannot crop from {}.".format(filename)
AssertionError: cannot crop from ABOUT/test/ABOUT_00001.

**Comment by mpc001** [comment]
Hi,

the preprocessing script is used for cropping LRW dataset by default, so the original LRW video directory should be passed to `--video-direc`.
