### ISSUE TITLE
How to run this model on 2 GPUs?

### ISSUE THREAD

**Issue by CXiaoDing** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#9]
Hi, thank you for your great work on lipreading. 
I want to implement this model on 2 GPUs, and I used **nn.DataParallel** to do it. But there have some problems in the function **__average_batch()_** in the **_model.py_** file, the error as follows:
IndexError: index 16 is out of bounds for dimension 0 with size 16.
Do you meet this problem?
Thank you very much! @mpc001

**Comment by mpc001** [comment]
Hi,

I didn't try multiple GPU. I suggest you could simply check for`lengths`, which seems out of bounds for tensor `x` in the function `_average_batch`.

**Comment by zhanghousen** [comment]
> Hi, thank you for your great work on lipreading.
> I want to implement this model on 2 GPUs, and I used **nn.DataParallel** to do it. But there have some problems in the function **__average_batch()_** in the **_model.py_** file, the error as follows:
> IndexError: index 16 is out of bounds for dimension 0 with size 16.
> Do you meet this problem?
> Thank you very much! @mpc001

Have you solved this problem? I have the same problem
